apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: credibl
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      imagePullSecrets:
      - name: secret
      containers:
      - name: nodeserver
        image: sheetalshevalkar/test-project:t1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
