apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: credible
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      imagePullSecrets:
      - name: secret
      nodeSelector:
        env: node2
      containers:
      - name: nodeserver
        image: sheetalshevalkar/test-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
